export const list = {
    top: [
        'none.cp',
        'normal1.cp',
        'normal2.cp',
        'prism.cp',
        'triangle.cp',
        'simpleS.cp',
        'simpleM.cp',
        'simpleL.cp',
        'worried.cp',
        'thin.cp',
    ],
    bottom: ['triangle.cp', 'smile.cp', 'rect.cp', 'sharp.cp', 'thin.cp', 'small.cp', 'Jagged_teeth.cp'],
    side: [
        'simple.cp',
        'circle.cp',
        'heart.cp',
        'arrow1.cp',
        'arrow2.cp',
        'arrow3.cp',
        'arrow4.cp',
        'rect1.cp',
        'rect2.cp',
        'thin1.cp',
        'thin2.cp',
    ],
};
