export const list = {
    top: [
        'default.cp',
        'none.cp',
        'normal1.cp',
        'normal2.cp',
        'prism.cp',
        'triangle.cp',
        'simpleS.cp',
        'simpleM.cp',
        'simpleL.cp',
        'worried.cp',
        'worriedL.cp',
        'thin.cp',
        'long.cp',
    ],
    bottom: [
        'default.cp',
        'triangle.cp',
        'smile.cp',
        'rect.cp',
        'sharp.cp',
        'thin.cp',
        'small.cp',
        'Jagged_teeth.cp',
        'tongue.cp',
        'arch.cp',
        'sharp_smile.cp',
        //'tears.cp',
    ],
    side: [
        'default.cp',
        'simple.cp',
        'big.cp',
        'circle.cp',
        'heart.cp',
        'arrow1.cp',
        'arrow2.cp',
        'arrow3.cp',
        'arrow4.cp',
        'arrow5.cp',
        'rect1.cp',
        'rect2.cp',
        'thin1.cp',
        'thin2.cp',
        'dia.cp',
        'arch.cp',
        'zigzag.cp',
        'angry.cp',
    ],
};

//preview option
export function getOptions(part, fileName) {
    return {
        face_reverse: options_list.face_reverse[part].includes(fileName),
        reverse: options_list.reverse[part].includes(fileName),
        order: options_list.order[part][fileName] ?? 0,
    };
}
const options_list = {
    face_reverse: { top: ['worriedL.cp'], bottom: [], left: [], right: [] },
    reverse: {
        top: ['none.cp', 'worriedL.cp'],
        bottom: [
            'triangle.cp',
            'smile.cp',
            'rect.cp',
            'sharp.cp',
            'thin.cp',
            'small.cp',
            'Jagged_teeth.cp',
            'tongue.cp',
            'sharp_smile.cp',
        ],
        left: ['big.cp', 'angry.cp'],
        right: [
            'simple.cp',
            'arrow1.cp',
            'arrow2.cp',
            'arrow3.cp',
            'arrow4.cp',
            'arrow5.cp',
            'rect1.cp',
            'rect2.cp',
            'thin1.cp',
            'thin2.cp',
            'dia.cp',
            'arch.cp',
            'zigzag.cp',
            'big.cp',
            'angry.cp',
        ],
    },
    order: {
        top: {
            'normal1.cp': 2,
            'normal2.cp': 2,
            'prism.cp': 2,
            'triangle.cp': 2,
            'simpleS.cp': 2,
            'simpleM.cp': 2,
            'simpleL.cp': 2,
            'worried.cp': 2,
            'thin.cp': 2,
        },
        bottom: {
            'smile.cp': 1,
            'rect.cp': 1,
            'thin.cp': 1,
            'small.cp': 1,
        },
        left: {},
        right: {},
    },
};
